### ISSUE TITLE
server crash occuring

### ISSUE THREAD

**Issue by chanzie** [TehNut/ChiselTones#1]
Most recent version of chisel ztones and chiseltones is throwing this server error
[14:51:11] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[14:51:11] [Server thread/ERROR] [FML/]: Caught exception from chiseltones
java.lang.NoSuchFieldError: enableAgon
    at tehnut.chiseltones.ChiselTones.addVariations(ChiselTones.java:32) ~[ChiselTones.class:1.7.10-1.0-3]
    at tehnut.chiseltones.ChiselTones.init(ChiselTones.java:26) ~[ChiselTones.class:1.7.10-1.0-3]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737) [Loader.class:?]
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[14:51:11] [Server thread/WARN] [FML/]: Can't revert to frozen GameData state without freezing first.
[14:51:11] [Server thread/INFO] [FML/]: Applying holder lookups
[14:51:11] [Server thread/WARN] [FML/]: Unable to lookup chisel:cobblestoneWall for public static team.chisel.block.BlockCarvableWall team.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[14:51:11] [Server thread/WARN] [FML/]: Unable to lookup chisel:obsidian2 for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.obsidian2. Is there something wrong with the registry?
[14:51:11] [Server thread/WARN] [FML/]: Unable to lookup chisel:voidstonerunic for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.voidstonerunic. Is there something wrong with the registry?
[14:51:11] [Server thread/WARN] [FML/]: Unable to lookup chisel:circuits for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.circuits. Is there something wrong with the registry?
[14:51:11] [Server thread/WARN] [FML/]: Unable to lookup Ztones:essenceFour for public static com.riciJak.Ztones.item.ItemZTNS com.riciJak.Ztones.init.ModItems.essenceFour. Is there something wrong with the registry?
[14:51:11] [Server thread/INFO] [FML/]: Holder lookups applied
[14:51:11] [Server thread/TRACE] [mcp/mcp]: Sending event FMLServerStoppedEvent to mod mcp
[14:51:11] [Server thread/TRACE] [mcp/mcp]: Sent event FMLServerStoppedEvent to mod mcp
[14:51:11] [Server thread/TRACE] [FML/FML]: Sending event FMLServerStoppedEvent to mod FML
[14:51:11] [Server thread/TRACE] [FML/FML]: Sent event FMLServerStoppedEvent to mod FML
[14:51:11] [Server thread/TRACE] [Forge/Forge]: Sending event FMLServerStoppedEvent to mod Forge
[14:51:11] [Server thread/TRACE] [Forge/Forge]: Sent event FMLServerStoppedEvent to mod Forge
[14:51:11] [Server thread/TRACE] [AM2-Preloader/AM2-Preloader]: Sending event FMLServerStoppedEvent to mod AM2-Preloader
[14:51:11] [Server thread/TRACE] [AM2-Preloader/AM2-Preloader]: Sent event FMLServerStoppedEvent to mod AM2-Preloader
[14:51:11] [Server thread/TRACE] [appliedenergistics2-core/appliedenergistics2-core]: Sending event FMLServerStoppedEvent to mod appliedenergistics2-core
[14:51:11] [Server thread/TRACE] [appliedenergistics2-core/appliedenergistics2-core]: Sent event FMLServerStoppedEvent to mod appliedenergistics2-core
[14:51:11] [Server thread/TRACE] [CodeChickenCore/CodeChickenCore]: Sending event FMLServerStoppedEvent to mod CodeChickenCore
[14:51:11] [Server thread/TRACE] [CodeChickenCore/CodeChickenCore]: Sent event FMLServerStoppedEvent to mod CodeChickenCore

**Comment by TehNut** [comment]
"Most recent" are not valid version numbers.

**Comment by chanzie** [comment]
those are what I downloaded from curse last night >.<

**Comment by TehNut** [comment]
Just give me version numbers...

**Comment by chanzie** [comment]
Chisel-2.9.2.8, ChiselTones-1.7.10-1.0-3

**Comment by TehNut** [comment]
What about ZTones? Is it reproducable? Gotta give me something to work with

**Comment by chanzie** [comment]
Ztones-1.7.10-1.0, it is occuring on every server startup with the mods installed, with and w/o liteloader, and across two seperate computers fresh world started to try and stop it and still didnt stop the error, I can try to back it down to those three mods and see if I can shoot in another mods direction but all run fine with the exception of ChiselTones upon adding ChiselTones is when the crashes started and upon removing it for the time being every thing is back to fine

**Comment by chanzie** [comment]
and wala there is the issue really old version of ztones downloaded for some reason instead of most recent on fixing it now

**Comment by chanzie** [comment]
ok close it I am sooooo sorry, looked at every version to double check up to date status other than ztones and that was the issue ztones is in 2.2.1 and for some reason it installed 1.0 last night
